module.exports = {
  rules: {
    'check-duplicate-taskname':'error',
    'conditional-flows': 'error',
    'intermediate-message':'error',
    'start-error-node':'error',
    'start-message':'error',
    'start-conditional':'error',
    'end-event-message':'error',
    'start-timer-node':'error',
    'intermediate-signal':'error',
    'intermediate-error':'error',
    'Input-output-for-humantask':'error',
    'intermediate-link':'error',
    'start-compensation':'error',
    'intermediate-compensation':'error',
    'intermediate-escalation':'error',
    'intermediate-timer':'error',
    'task-type-not-specified': 'error',
    'end-event-required': 'error',
    'exclusive-same-condition':'error',
    'start-error-node':'error',
    'event-sub-process-typed-start-event': 'error',
    'fake-join': 'warn',
    'label-required': 'error',
    'exclusive-gateway-condition':'error',
    'inclusive-gateway-condition':'error',
    'naming':'error',
    'no-bpmndi': 'error',
    'no-complex-gateway': 'error',
    'no-disconnected': 'error',
    'no-duplicate-sequence-flows': 'error',
    'no-gateway-join-fork': 'error',    
    'no-implicit-split': 'error',
    'no-inclusive-gateway': 'error',
    'single-blank-start-event': 'error',
    'single-event-definition': 'error',
    'start-event-required': 'error',
    'sub-process-blank-start-event': 'error',
    'superfluous-gateway': 'error',
    
  }
};
